### ISSUE TITLE
[BUG] No match found

### ISSUE THREAD

**Issue by BartosB13** [thedutchruben/TDRPlaytime#129]
This error appears on the console. What can you do about it?

```
[17:56:43 WARN]: [TDRPlaytime] Plugin TDRPlaytime v1.14.1 generated an exception while executing task 635173
java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:644) ~[?:?]
        at nl.thedutchruben.mccore.Mccore.lambda$getUpdate$10(Mccore.java:224) ~[playtime-1.14.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by oskarbukovsky** [comment]
I get similar error, but different server
```
[Mon 22:46:59 WARN  nl.thedutchruben.playtime.PlaytimePlugin] [TDRPlaytime] Plugin TDRPlaytime v1.14.0 generated an exception while executing task 869
java.lang.IllegalStateException: No match found
    at java.base/java.util.regex.Matcher.checkMatch(Matcher.java:1852)
    at java.base/java.util.regex.Matcher.group(Matcher.java:687)
    at nl.thedutchruben.mccore.Mccore.lambda$getUpdate$10(Mccore.java:224)
    at TRANSFORMER/forge@47.2.32/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
    at TRANSFORMER/forge@47.2.32/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
```
