### ISSUE TITLE
Server stopping

### ISSUE THREAD

**Issue by tamperplay** [thedutchruben/TDRPlaytime#15]
When the server is turned off, this error appears

`[18:05:26] [Server thread/INFO]: [TDRPlaytime] Disabling TDRPlaytime v1.8.1
[18:05:26] [Server thread/ERROR]: Error occurred while disabling TDRPlaytime v1.8.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:537) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:177) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:146) ~[patched_1.17.1.jar:git-Airplane-55]
	at nl.thedutchruben.playtime.Playtime.update(Playtime.java:169) ~[?:?]
	at nl.thedutchruben.playtime.Playtime.onDisable(Playtime.java:145) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.17.1.jar:git-Airplane-55]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:452) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1030) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:809) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311) ~[patched_1.17.1.jar:git-Airplane-55]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-55]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by thedutchruben** [comment]
Hello,
tis error is reported to me and wil be fixt in the next version that will be released this week.

**Comment by thedutchruben** [comment]
Hello, 
This error has been solved in the latest version, which you can download here: https://www.spigotmc.org/resources/tdrplaytime-rewards-mysql.47894/update?update=422840
