### ISSUE TITLE
Mysql connection

### ISSUE THREAD

**Issue by tamperplay** [thedutchruben/TDRPlaytime#16]
The plugin loses connection to the database when it works for more than 10 hours, the wait timeout on the mysql side costs 30 hours, I think it's the plugin's fault?
AirPlane 1.17.1
Java 16
Mysql 5.7
`[16:48:20] [User Authenticator #1/INFO]: UUID of player tamperplay is f0434b78-3afd-36e7-b727-325e4ddb47ce
[16:48:20] [Server thread/INFO]: Base value for attribute Max Health for entity tamperplay set to 2.0
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 49 648 600 milliseconds ago. The last packet sent successfully to the server was 49 648 600 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at nl.thedutchruben.playtime.database.MysqlDatabase.lambda$getPlayTimeByUUID$0(MysqlDatabase.java:81)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 49 648 600 milliseconds ago. The last packet sent successfully to the server was 49 648 600 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:577)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:632)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:948)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	... 9 more
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: Caused by: java.net.SocketException: Обрыв канала
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1045)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:342)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1287)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:568)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	... 13 more
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1664)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1580)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at nl.thedutchruben.playtime.database.MysqlDatabase.lambda$getPlayTimeByUUID$0(MysqlDatabase.java:90)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:573)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1595)
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: 	... 9 more
[16:48:20] [ForkJoinPool.commonPool-worker-3/WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 49 648 600 milliseconds ago. The last packet sent successfully to the server was 49 648 600 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.`

**Comment by thedutchruben** [comment]
Hello,
thanks for reporting i added a reconnect in the next version that will release soon

**Comment by tamperplay** [comment]
???

**Comment by WongIong** [comment]
edit the database.yml
added a value "autoreconnect: true"

**Comment by thedutchruben** [comment]
Hey,
The database now reconnects automatically.
  You can download the new version here: https://www.spigotmc.org/resources/tdrplaytime-rewards-mysql.47894/update?update=422840
