### ISSUE TITLE
Warn after /stop

### ISSUE THREAD

**Issue by WongIong** [thedutchruben/TDRPlaytime#19]
[00:37:00] [Server thread/INFO]: [TDRPlaytime] Disabling TDRPlaytime v1.8.1
[00:37:00] [Server thread/ERROR]: Error occurred while disabling TDRPlaytime v1.8.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[patched_1.17.1.jar:git-Paper-216]
	at nl.thedutchruben.playtime.Playtime.update(Playtime.java:169) ~[playtime-1.8.1.jar:?]
	at nl.thedutchruben.playtime.Playtime.onDisable(Playtime.java:145) ~[playtime-1.8.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:519) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:512) ~[patched_1.17.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:469) ~[patched_1.17.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:974) ~[patched_1.17.1.jar:git-Paper-216]
	at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:806) ~[patched_1.17.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1253) ~[patched_1.17.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patched_1.17.1.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by thedutchruben** [comment]
Hello, 
This error has been solved in the latest version, which you can download here: https://www.spigotmc.org/resources/tdrplaytime-rewards-mysql.47894/update?update=422840
