### ISSUE TITLE
1.18 Dont working

### ISSUE THREAD

**Issue by LukyTechnology** [thedutchruben/TDRPlaytime#26]
Hello! When i connect plugin to MySQL and join to server console give me this error 

[20:50:19] [Craft Scheduler Thread - 20 - TDRPlaytime/WARN]: [TDRPlaytime] Plugin TDRPlaytime v1.10.0 generated an exception while executing task 28
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
	at nl.thedutchruben.playtime.Playtime.update(Playtime.java:208) ~[Playtime-1.10.0.jar:?]
	at nl.thedutchruben.playtime.Playtime.lambda$onEnable$2(Playtime.java:147) ~[Playtime-1.10.0.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-145]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-145]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-145]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

And When i use /playtime console SPAMING lots of errors (https://paste.gg/p/anonymous/6020db4fc18f46b4b3d79b6411c2bffb) and this errors spam infinite

**Comment by thedutchruben** [comment]
hi,

This error comes if there is no data from the join.
Is there any data in the database?
If so is there an error while joining?

**Comment by LukyTechnology** [comment]
In database are data from my Lobby server where plugin working sucesfully. This is error when player join to server

[Craft Scheduler Thread - 20 - TDRPlaytime/WARN]: [TDRPlaytime] Plugin TDRPlaytime v1.10.0 generated an exception while executing task 28
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
at nl.thedutchruben.playtime.Playtime.update(Playtime.java:208) ~[Playtime-1.10.0.jar:?]
at nl.thedutchruben.playtime.Playtime.lambda$onEnable$2(Playtime.java:147) ~[Playtime-1.10.0.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-145]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-145]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-145]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by thedutchruben** [comment]
Okay so the playtime database also contains data because then I'm going to see how I can do this

**Comment by LukyTechnology** [comment]
Hi! Are you working on fix this error ?

**Comment by thedutchruben** [comment]
In the newest version (1.10.6) the error should not happen

**Comment by LukyTechnology** [comment]
Yes, its working! Thanks!
