### ISSUE TITLE
Plugin TDRPlaytime v1.10.7 generated an exception while executing task 18

### ISSUE THREAD

**Issue by yuma-dev** [thedutchruben/TDRPlaytime#40]
```
30.06 11:42:47 [Server] WARN [TDRPlaytime] Plugin TDRPlaytime v1.10.7 generated an exception while executing task 18
30.06 11:42:47 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
30.06 11:42:47 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.19.jar:git-Paper-40]
30.06 11:42:47 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.19.jar:git-Paper-40]
30.06 11:42:47 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.19.jar:git-Paper-40]
30.06 11:42:47 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[paper-1.19.jar:git-Paper-40]
30.06 11:42:47 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[paper-1.19.jar:git-Paper-40]
30.06 11:42:47 [Server] INFO at nl.thedutchruben.playtime.updatechecker.UpdateChecker.lambda$checkNow$5(UpdateChecker.java:220) ~[playtime-1.10.7.jar:?]
30.06 11:42:47 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-40]
30.06 11:42:47 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-40]
30.06 11:42:47 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
30.06 11:42:47 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
30.06 11:42:47 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
30.06 11:42:47 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by thedutchruben** [comment]
Hey,

In the upcoming release this will be fixed.

Thanks for reporting.

**Comment by yuma-dev** [comment]
When will this release come out? Or is there any beta I can opt in?

**Comment by thedutchruben** [comment]
This is fixed by the latest update https://www.spigotmc.org/resources/tdr-playtime-rewards-mysql.47894/update?update=466897
