### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by WongIong** [thedutchruben/TDRPlaytime#42]
[07:38:05] [Server thread/INFO]: [TDRPlaytime] Enabling TDRPlaytime v1.11.0*
[07:38:05] [Server thread/ERROR]: Error occurred while enabling TDRPlaytime v1.11.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.FileConfigurationOptions org.bukkit.configuration.file.FileConfigurationOptions.setHeader(java.util.List)'
	at nl.thedutchruben.playtime.Playtime.onEnable(Playtime.java:152) ~[playtime-1.11.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:38:05] [Server thread/INFO]: [TDRPlaytime] Disabling TDRPlaytime v1.11.0

**Comment by thedutchruben** [comment]
This should be resolved in the latest version: https://www.spigotmc.org/resources/tdr-playtime-rewards-mysql.47894/update?update=473537
