### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by KyleStance** [thedutchruben/TDRPlaytime#45]
[Server thread/INFO]: [TDRPlaytime] Enabling TDRPlaytime v1.11.1*
[Server thread/ERROR]: Error occurred while enabling TDRPlaytime v1.11.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.FileConfigurationOptions org.bukkit.configuration.file.FileConfigurationOptions.setHeader(java.util.List)'
  at nl.thedutchruben.playtime.Playtime.onEnable(Playtime.java:176) ~[playtime-1.11.1.jar:?]
  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1428]
  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1428]
  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
  at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Purpur-1428]
  at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Purpur-1428]
  at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736) ~[patched_1.17.1.jar:git-Purpur-1428]
  at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[patched_1.17.1.jar:git-Purpur-1428]
  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
  at java.lang.Thread.run(Unknown Source) ~[?:?]
[Server thread/INFO]: [TDRPlaytime] Disabling TDRPlaytime v1.11.1

**Comment by thedutchruben** [comment]
Good day,

What version minecraft server are you using?

**Comment by KyleStance** [comment]
> Good day,
> 
> What version minecraft server are you using?

1.16.5 and 1.18.2

**Comment by KyleStance** [comment]
> Good day,
> 
> What version minecraft server are you using?

[18:01:48 INFO]: [TDRPlaytime] Enabling TDRPlaytime v1.11.2*
[18:01:48 ERROR]: Error occurred while enabling TDRPlaytime v1.11.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.FileConfigurationOptions org.bukkit.configuration.file.FileConfigurationOptions.setHeader(java.util.List)'
at nl.thedutchruben.playtime.Playtime.onEnable(Playtime.java:168) ~[playtime-1.11.2.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-408]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-408]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
at java.lang.Thread.run(Unknown Source) ~[?:?]
[18:01:48 INFO]: [TDRPlaytime] Disabling TDRPlaytime v1.11.2

**Comment by thedutchruben** [comment]
This should be resolved in the latest version: https://www.spigotmc.org/resources/tdr-playtime-rewards-mysql.47894/update?update=473537
