### ISSUE TITLE
[error] Top placeholders not work

### ISSUE THREAD

**Issue by Wgis** [thedutchruben/TDRPlaytime#53]
**Version**: 
1.11.5

**Try**:
> /papi parse me %tdrplaytime_top_time_1%

**Catch**:
`[00:08:45 WARN]: java.sql.SQLSyntaxErrorException: Table 'j92644957_global.playtime_' doesn't exist
[00:08:45 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[00:08:45 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[00:08:45 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[00:08:45 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[00:08:45 WARN]:        at playtime-1.11.5.jar//nl.thedutchruben.playtime.database.MysqlDatabase.getTopPlaceTime(MysqlDatabase.java:240)
[00:08:45 WARN]:        at playtime-1.11.5.jar//nl.thedutchruben.playtime.extentions.PlaceholderAPIExpansion.onPlaceholderRequest(PlaceholderAPIExpansion.java:190)
[00:08:45 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[00:08:45 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[00:08:45 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[00:08:45 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118)
[00:08:45 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:58)
[00:08:45 WARN]:        at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114)
[00:08:45 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:08:45 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[00:08:45 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911)
[00:08:45 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[00:08:45 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[00:08:45 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[00:08:45 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[00:08:45 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2293)
[00:08:45 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2247)
[00:08:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[00:08:45 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:08:45 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:08:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[00:08:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:08:45 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1361)
[00:08:45 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[00:08:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[00:08:45 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1338)
[00:08:45 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1331)
[00:08:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[00:08:45 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1309)
[00:08:45 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1197)
[00:08:45 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[00:08:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by WongIong** [comment]
I have the same issue but got no errors.
![image](https://user-images.githubusercontent.com/36799194/208998657-4702d009-bb8b-4906-bd5e-bd1effcee3c7.png)
