### ISSUE TITLE
Plugin TDRPlaytime v1.11.6 generated an exception

### ISSUE THREAD

**Issue by BartosB13** [thedutchruben/TDRPlaytime#80]
Any chance of help? Is this error due to the plugin itself or something external?
Paper 1.19.4

```
[13:41:43 WARN]: [TDRPlaytime] Plugin TDRPlaytime v1.11.6 generated an exception while executing task 7053372
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.Map.get(Object)" is null
        at nl.thedutchruben.playtime.Playtime.lambda$update$24(Playtime.java:393) ~[playtime-1.11.6.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-550]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by thedutchruben** [comment]
Hi,

what database type are you using?

**Comment by BartosB13** [comment]
Dzięki za odpowiedź

MySQL

**Comment by BartosB13** [comment]
When I typed /playtime reload, this error popped up, maybe this log will be useful for something

```
[11:51:49 INFO]: Bartos13 issued server command: /playtime reload
[11:51:49 WARN]: java.lang.reflect.InvocationTargetException
[11:51:49 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:51:49 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[11:51:49 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:51:49 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[11:51:49 WARN]:        at playtime-1.11.6.jar//nl.thedutchruben.mccore.spigot.commands.CommandRegistry.onCommand(CommandRegistry.java:222)
[11:51:49 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:51:49 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[11:51:49 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:929)
[11:51:49 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[11:51:49 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[11:51:49 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
[11:51:49 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)
[11:51:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[11:51:49 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2257)
[11:51:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[11:51:49 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[11:51:49 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:51:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:51:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:51:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[11:51:49 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[11:51:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[11:51:49 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[11:51:49 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[11:51:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:51:49 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[11:51:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[11:51:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[11:51:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:51:49 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "nl.thedutchruben.playtime.Playtime$LastCheckedData.getTime()" because the return value of "java.util.Map.get(Object)" is null
[11:51:49 WARN]:        at playtime-1.11.6.jar//nl.thedutchruben.playtime.Playtime.forceSave(Playtime.java:411)
[11:51:49 WARN]:        at playtime-1.11.6.jar//nl.thedutchruben.playtime.command.PlayTimeCommand.reload(PlayTimeCommand.java:130)
[11:51:49 WARN]:        ... 29 more
```
